name: Belly
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  cached_network_image: ^2.0.0-rc
  shared_preferences: ^0.5.3+4
  pin_code_text_field: ^1.5.1
  jiffy: ^2.1.2
  stripe_payment: ^1.0.6
  flutter_credit_card: ^0.1.3
  firebase_messaging: ^6.0.9
  flutter_pagewise: ^1.2.3
  provider: ^4.0.4
  image_picker: ^0.6.2+3
  cloud_firestore: ^0.13.4
  google_maps_flutter: ^0.5.21+12
  location: ^2.3.5
  connectivity: 0.4.6+2
  flutter_html: ^1.0.0
  url_launcher: ^5.4.7
  flutter_rating_bar: ^3.0.1+1
  geocoder: ^0.2.1
  razorpay_flutter: ^1.2.2
  pull_to_refresh: ^1.6.1
  

dependency_overrides:
  firebase_core: 0.4.4

dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  image_path: "images/icon.png"
  
flutter:
  uses-material-design: true

  assets:
    - images/icons/remove_disabled_button.png
    - images/icons/remove_enabled_button.png
    - images/icons/thin_add_button.png
    - images/icons/camera_icon.png
    - images/splashscreen.png
    - images/offer0.jpg
    - images/offer1.jpg
    - images/offer2.jpg
    - images/offer3.jpg
    - images/icon.png
    - images/

  fonts:
    - family: MontserratRegular
      fonts:
        - asset: fonts/montserrat.regular.ttf
          weight: 700
    - family: MontserratMedium
      fonts:
        - asset: fonts/Montserrat-Medium.ttf
          weight: 700
    - family: NotoSansJP
      fonts:
        - asset: fonts/NotoSansJP-Bold.otf
        - asset: fonts/NotoSansJP-Light.otf
        - asset: fonts/NotoSansJP-Medium.otf
        - asset: fonts/NotoSansJP-Regular.otf
          weight: 700
    - family: MyIcon
      fonts:
        - asset: fonts/MyIcon.ttf
    - family: BellyCart
      fonts:
        - asset: fonts/BellyCart.ttf